version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: bch2-apps-forge-pool_web_1
      APP_PORT: 80

  web:
    image: ghcr.io/bitcoincashii/forge-pool-web:latest
    restart: on-failure
